### ISSUE TITLE
Comments for announcements (User Side)

### ISSUE THREAD

**Issue by arthurvicencio** [arthurvicencio/Project_Cappuccino#5]
Announcement comments table schema

CREATE TABLE `announcement_comments` (
  `comment_id` int(11) NOT NULL,
  `announcement_id` int(11) NOT NULL,
  `constituent_id` int(11) NOT NULL,
  `comment` varchar(500) NOT NULL,
  `date_posted` datetime NOT NULL,
  `status` enum('read','unread') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `announcement_comments`
  ADD PRIMARY KEY (`comment_id`);

ALTER TABLE `announcement_comments`
  MODIFY `comment_id` int(11) NOT NULL AUTO_INCREMENT;

**Comment by kyle-espino** [comment]
Done. Thanks man. 👌
